(define (helper sub_lst)
        (if (nil? (cdr sub_lst))
                (car sub_lst)
                (helper (cdr sub_lst))
            )
        )

(define (reverse lst)
    (if (null? lst)
        '()
        (if (null? (cdr lst))
             (list (car lst))
            (append (reverse (cdr lst)) (list (car lst)))
                )
            )
    )
